### ISSUE TITLE
Stuffit 5 Resource Fork Failure

### ISSUE THREAD

**Issue by agg23** [ParksProjets/Maconv#1]
I stumbled on your project today and was very excited at the possibilities it can bring. However, Stuffit Algorithm 13 seems to have issues extracting the resource forks much of the time. For example, with [Stuffit Deluxe 4.0.1 on Macintosh Garden](http://macintoshgarden.org/sites/macintoshgarden.org/files/apps/STUFFITDLX401.SIT), the following errors occur:

`WARNING: ressource fork of 'StuffIt Deluxe™ 4.0 Updater' couldn't be extracted (Algo13: invalid compressed data [code])
WARNING: ressource fork of 'StuffIt Deluxe™ Disk 2.img' couldn't be extracted (Algo13: invalid compressed data [code])
WARNING: ressource fork of 'StuffIt Deluxe™.img' couldn't be extracted (Algo13: invalid compressed data [code])
WARNING: ressource fork of 'StuffIt registration' couldn't be extracted (Algo13: invalid compressed data [code])`

Is this a known issue?

I am working on a project to reorganize all of the files served by Macintosh Garden, and this tool in particular could be very useful in normalizing the format of the files (or even better, converting them all to AppleDouble for use in Netatalk). I would be glad to help if there was some need.

**Comment by ParksProjets** [comment]
Hi!

I have fixed this issue in the last commit. In fact, the problem was on all Stuffit 5 archives with both data and ressource forks, the offset of the ressource fork was wrong.

Note that **AppleDouble** is not yet supported by **Maconv** (even if there is `conv/appledouble.cc` in the sources).

Thanks for reporting this issue.
